// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmffbpzltkdmzizrdvfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZmZicHpsdGtkbXppenJkdmZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTQ0OTgsImV4cCI6MjA1OTc3MDQ5OH0.vse8Rcm8NuWQTf0F9zj-Bz8WrpA5n5MKQhQnMnn9h_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);